begin;
do $$
declare o uuid:=gen_random_uuid();a1 uuid:=gen_random_uuid();a2 uuid:=gen_random_uuid();h uuid:=gen_random_uuid();sender uuid:=gen_random_uuid();u uuid;sid uuid;registration1 uuid;registration2 uuid;agency1 uuid;agency2 uuid;req uuid;key uuid;answer jsonb;denied boolean;room uuid:=gen_random_uuid();gift uuid;
begin
 foreach u in array array[o,a1,a2,h,sender] loop
  insert into auth.users(id,email,email_confirmed_at,is_anonymous) values(u,u::text||'@test.invalid',now(),false);
  insert into auth.sessions(id,user_id) values(gen_random_uuid(),u);
 end loop;
 update phase3.system_authority set owner_id=o,main_partner_id=null where singleton;
 select id into sid from auth.sessions where user_id=a1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a1,'session_id',sid,'aal','aal1')::text,true);
 key:=gen_random_uuid();answer:=public.phase4_agency_action('register','{"kind":"host","name":"QA agency one","contact":"QA contact","reason":"QA registration"}',key);registration1:=(answer->>'id')::uuid;
 if public.phase4_agency_action('register','{"kind":"host","name":"QA agency one","contact":"QA contact","reason":"QA registration"}',key)<>answer then raise exception 'Registration retry duplicated';end if;
 denied:=false;begin perform public.phase4_agency_action('approve_registration',jsonb_build_object('id',registration1,'note','QA approval','commission_percent',10),gen_random_uuid());exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Applicant self-approved';end if;
 select id into sid from auth.sessions where user_id=a2;perform set_config('request.jwt.claims',jsonb_build_object('sub',a2,'session_id',sid,'aal','aal1')::text,true);
 answer:=public.phase4_agency_action('register','{"kind":"host","name":"QA agency two","contact":"QA contact","reason":"QA registration"}',gen_random_uuid());registration2:=(answer->>'id')::uuid;
 if jsonb_array_length(public.phase4_agency_state()->'registrations')<>1 then raise exception 'Private registration leaked';end if;
 select id into sid from auth.sessions where user_id=o;perform set_config('request.jwt.claims',jsonb_build_object('sub',o,'session_id',sid,'aal','aal1')::text,true);
 answer:=public.phase4_agency_action('approve_registration',jsonb_build_object('id',registration1,'note','QA review approval','commission_percent',10),gen_random_uuid());agency1:=(answer->>'agency_id')::uuid;
 answer:=public.phase4_agency_action('approve_registration',jsonb_build_object('id',registration2,'note','QA review approval','commission_percent',20),gen_random_uuid());agency2:=(answer->>'agency_id')::uuid;
 denied:=false;begin perform public.phase4_agency_action('edit',jsonb_build_object('id',agency1,'name','QA valid name','commission_percent',101),gen_random_uuid());exception when others then denied:=true;end;if not denied then raise exception 'Invalid commission accepted';end if;
 perform public.phase4_agency_action('edit',jsonb_build_object('id',agency1,'name','QA edited name','commission_percent',12),gen_random_uuid());
 select id into sid from auth.sessions where user_id=h;perform set_config('request.jwt.claims',jsonb_build_object('sub',h,'session_id',sid,'aal','aal1')::text,true);
 answer:=public.phase4_agency_action('join',jsonb_build_object('agency_id',agency1,'reason','QA host join'),gen_random_uuid());req:=(answer->>'id')::uuid;
 select id into sid from auth.sessions where user_id=a1;perform set_config('request.jwt.claims',jsonb_build_object('sub',a1,'session_id',sid,'aal','aal1')::text,true);
 perform public.phase4_agency_action('accept_join',jsonb_build_object('id',req),gen_random_uuid());
 if not exists(select 1 from public.agency_members where user_id=h and agency_id=agency1) then raise exception 'Host not attached';end if;
 insert into public.rooms(id,owner_id,title) values(room,sender,'QA agency room');insert into public.room_members(room_id,user_id) values(room,sender),(room,h);
 update public.wallets set coins=100 where user_id=sender;
 select id into sid from auth.sessions where user_id=sender;perform set_config('request.jwt.claims',jsonb_build_object('sub',sender,'session_id',sid,'aal','aal1')::text,true);
 answer:=public.phase3_send_gift(room,h,'g1',1,gen_random_uuid(),10);gift:=(answer->>'id')::uuid;
 if not exists(select 1 from public.gift_events where id=gift and agency_id=agency1) then raise exception 'Gift agency snapshot missing';end if;
 select id into sid from auth.sessions where user_id=h;perform set_config('request.jwt.claims',jsonb_build_object('sub',h,'session_id',sid,'aal','aal1')::text,true);
 answer:=public.phase4_agency_action('join',jsonb_build_object('agency_id',agency2,'reason','QA host transfer'),gen_random_uuid());req:=(answer->>'id')::uuid;
 if answer->>'status'<>'pending_old' then raise exception 'Old approval bypassed';end if;
 select id into sid from auth.sessions where user_id=a2;perform set_config('request.jwt.claims',jsonb_build_object('sub',a2,'session_id',sid,'aal','aal1')::text,true);
 denied:=false;begin perform public.phase4_agency_action('accept_join',jsonb_build_object('id',req),gen_random_uuid());exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Transfer bypassed old owner';end if;
 select id into sid from auth.sessions where user_id=a1;perform set_config('request.jwt.claims',jsonb_build_object('sub',a1,'session_id',sid,'aal','aal1')::text,true);
 perform public.phase4_agency_action('approve_old',jsonb_build_object('id',req),gen_random_uuid());
 select id into sid from auth.sessions where user_id=a2;perform set_config('request.jwt.claims',jsonb_build_object('sub',a2,'session_id',sid,'aal','aal1')::text,true);
 perform public.phase4_agency_action('accept_join',jsonb_build_object('id',req),gen_random_uuid());
 if not exists(select 1 from public.agency_members where user_id=h and agency_id=agency2) then raise exception 'Approved transfer not applied';end if;
 if not exists(select 1 from public.gift_events where id=gift and agency_id=agency1) then raise exception 'Historic gift agency changed';end if;
 select id into sid from auth.sessions where user_id=h;perform set_config('request.jwt.claims',jsonb_build_object('sub',h,'session_id',sid,'aal','aal1')::text,true);
 answer:=public.phase4_agency_action('join',jsonb_build_object('agency_id',agency1,'reason','QA dispute transfer'),gen_random_uuid());req:=(answer->>'id')::uuid;
 denied:=false;begin perform public.phase4_agency_action('exception_transfer',jsonb_build_object('id',req,'note','QA completed investigation'),gen_random_uuid());exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Host self-authorized exception';end if;
 select id into sid from auth.sessions where user_id=o;perform set_config('request.jwt.claims',jsonb_build_object('sub',o,'session_id',sid,'aal','aal1')::text,true);
 perform public.phase4_agency_action('exception_transfer',jsonb_build_object('id',req,'note','QA completed investigation'),gen_random_uuid());
 perform public.phase4_agency_action('close',jsonb_build_object('id',agency2,'note','QA close preserving history'),gen_random_uuid());
 if not exists(select 1 from public.security_audit where action='agency_exception_transfer' and details->'data'->>'note'='QA completed investigation') then raise exception 'Exception audit absent';end if;
end $$;
rollback;
select 'PASS: agency registration privacy/idempotency, admin review/settings/close, member approval, old-agent transfer consent, investigated exception and immutable gift snapshot; fixtures rolled back' as result;
